### ISSUE TITLE
need update

### ISSUE THREAD

**Issue by Wilhelm111** [iobroker-community-adapters/ioBroker.homepilot#20]
Since the Firmwareupdate 5.0 the Adapter does not work.
Rademacher changed the API.
(Same Problem with Homebridge)

**Comment by homecineplexx** [comment]
You can use my adapter... It's version >=5.0.39 and you can find it on github under homepilot20

**Comment by Wilhelm111** [comment]
homecineplexx thx for the great work.
You make me happy :) 
Is there a Problem with the actually Firmwareupdate 5.041 ? Should i update?

Grettings
Wilhelm

**Comment by homecineplexx** [comment]
I know no issue... You can
