### ISSUE TITLE
Instance cant connect to homepilot

### ISSUE THREAD

**Issue by Ced1999** [iobroker-community-adapters/ioBroker.homepilot#33]
The Homepilot Adapter cant connect to the device, but the homepilot webinterface is perfectly reachable in the browser.
It does not matter if i leave the ip at homepilot.local or manually type in the IP i always get the same error as below

</html>
</body>

<body>
<html>

homepilot.0 | 2022-06-30 00:39:04.378 | warn | Cannot connect to Homepilot: null
-- | -- | -- | --
homepilot.0 | 2022-06-30 00:39:04.363 | debug | finished reading Homepilot Data
homepilot.0 | 2022-06-30 00:39:04.360 | debug | reading homepilot JSON ...
homepilot.0 | 2022-06-29 22:38:52.358 | debug | Homepilot adapter started...
homepilot.0 | 2022-06-29 22:38:52.358 | debug | Homepilot station and ioBroker synchronize every 12s
homepilot.0 | 2022-06-29 22:38:52.358 | debug | initializing objects
homepilot.0 | 2022-06-29 22:38:52.349 | info | starting. Version 1.1.6 in /opt/iobroker/node_modules/iobroker.homepilot, node: v14.19.3, js-controller: 4.0.23
homepilot.0 | 2022-06-29 22:38:52.264 | debug | States connected to redis: 127.0.0.1:9000
homepilot.0 | 2022-06-29 22:38:52.253 | debug | States create User PubSub Client
homepilot.0 | 2022-06-29 22:38:52.253 | debug | States create System PubSub Client
homepilot.0 | 2022-06-29 22:38:52.247 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
homepilot.0 | 2022-06-29 22:38:52.234 | debug | Objects connected to redis: 127.0.0.1:9001
homepilot.0 | 2022-06-29 22:38:52.232 | debug | Objects client initialize lua scripts
homepilot.0 | 2022-06-29 22:38:52.208 | debug | Objects create User PubSub Client
homepilot.0 | 2022-06-29 22:38:52.208 | debug | Objects create System PubSub Client
homepilot.0 | 2022-06-29 22:38:52.208 | debug | Objects client ready ... initialize now
homepilot.0 | 2022-06-29 22:38:52.192 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
host.iobrokerlxc | 2022-06-29 22:38:51.863 | info | instance system.adapter.homepilot.0 started with pid 1316
host.iobrokerlxc | 2022-06-29 22:38:49.374 | info | instance system.adapter.homepilot.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)

**Comment by KlausStoertebeker** [comment]
Hi,
I have exactly the same problem and log entries, but I'm running this configuration:

Adapter: **Version 1.1.6 in /opt/iobroker/node_modules/iobroker.homepilot**
JSNode: **v18.7.0**
JS-Controller: **4.0.23**

I bought one [Rademacher Bridge 9492](https://service.rademacher.de/hc/article_attachments/4455444015378/VBD-708-1-_02.22__Bridge_DE-EN_Internet.pdf) and four [Rademacher RolloTron Basis DuoFern 1200](https://service.rademacher.de/hc/article_attachments/4408402421394/VBD-696-1-_10.21__RolloTron-Basis-DuoFern-1200-RolloTron_Basic_DuoFern_1200_DE-EN_Internet.pdf) and it would be very nice if someone could help me and **Ced1999** to get our equipment running :-)
Thanks in advance

"Klaus"

**Comment by homecineplexx** [comment]
You Must use the homepilot20 ..you can also find this in dlthe Forum If you can use the search function
